local M = {
  Alternative   = "alternative",
  Append        = "append",
  Body          = "body",
  Call          = "call",
  Comment       = "comment",
  Condition     = "condition",
  ForInit       = "for_init",
  ForLoop       = "for_loop",
  ForeachElem   = "foreach_elem",
  ForeachList   = "foreach_list",
  Global        = "global",
  Index         = "index",
  Local         = "local",
  Name          = "name",
  Number        = "number",
  Output        = "output",
  Position      = "position",
  Scope         = "scope",
  String        = "string",
  Special       = "special",
  WhenLabel     = "when_label",
  ScopeCase     = "case",
  ScopeWhen     = "when",
  ScopeOthers   = "others",
  ScopeFor      = "for",
  ScopeForeach  = "foreach",
  ScopeIf       = "if",
  ScopeElseIf   = "elseif",
  ScopeElse     = "else",
  ScopeParallel = "parallel",
  ScopeSwitch   = "switch",
  ScopeWhile    = "while",
}

return M
